Cw module
elhamod/taming-transformers pull request #4
Opened 2022-12-12 11:35 UTC by mridulkhurana

2022-12-16 16:17 UTC, elhamod requested changes

2022-12-16 16:17 UTC, elhamod commented on analysis/generate_with_transformer.py
> +    main(config)
I would rather you separate this into two files. It is generally not nice to keep commenting code to make something work. Doing that in config files is fine, but not code.

2022-12-16 16:17 UTC, elhamod commented on analysis/model_performance.py
> +    # model = load_CWVQGAN(config, ckpt_path=ckpt_path, data=dataset.data, cuda=(DEVICE is not None))
Same here. Either add a flag or make a new file, depending how much code is shared.

2022-12-16 16:17 UTC, elhamod commented on analysis/test_resnet.py
Same here

2022-12-16 16:17 UTC, elhamod commented on configs/archived/custom_vqgan-256img-phylo-vqvae.yaml
>            perceptual_weight: 0.0
nit remove empty space changes to simplify review

2022-12-17 00:05 UTC, mridulkhurana commented on analysis/generate_with_transformer.py
> +    main(config)
created a new file generate_with_transformer_cw.py and the original one is unchanged now

2022-12-17 00:06 UTC, mridulkhurana commented on analysis/test_resnet.py
created a new file test_resnet_cw.py and the original one is unchanged now

2022-12-17 00:06 UTC, mridulkhurana commented on analysis/model_performance.py
> +    # model = load_CWVQGAN(config, ckpt_path=ckpt_path, data=dataset.data, cuda=(DEVICE is not None))
added a config to evaluate between model loading of phly vs CW

2022-12-17 00:07 UTC, mridulkhurana commented on configs/archived/custom_vqgan-256img-phylo-vqvae.yaml
>            perceptual_weight: 0.0
removed !

2022-12-17 18:05 UTC, elhamod approved these changes

2022-12-17 18:05 UTC, merged