adding LSF related files
elhamod/taming-transformers pull request #5
Opened 2022-12-15 05:46 UTC by harishB97

2022-12-16 16:17 UTC, elhamod requested changes

2022-12-16 16:17 UTC, elhamod commented on taming/models/LSFautoencoder.py
> +        # self.LSF_disentangler = LSFDisentangler(**LSF_args)
Remove this and any unnecessary comments

2022-12-16 16:17 UTC, elhamod commented on taming/models/LSFautoencoder.py
> +        # Based on the approach mentioned in paper
Add link to paper

2022-12-17 19:30 UTC, harishB97 commented on taming/models/LSFautoencoder.py
> +        # self.LSF_disentangler = LSFDisentangler(**LSF_args)
Removed all unnecessary comments. If you meant to remove the if statement in line 45, i dont think that can be done since its needed

2022-12-17 19:31 UTC, harishB97 commented on taming/models/LSFautoencoder.py
> +        # Based on the approach mentioned in paper
Lind added

2022-12-17 20:07 UTC, elhamod approved these changes

2022-12-17 20:07 UTC, merged